############################################################
# Hugo Pure & Simple - 主設定檔
############################################################

# --- 基礎設定 (必填) ---
# baseURL 是您網站的最終網址。
# 對於 GitHub Pages，格式為 "https://<您的 GitHub 帳號>.github.io/<您的儲存庫名稱>/"
#
# ⚠️ 這是部署成功的關鍵，請務必修改！
# 下列網址以範例儲存庫 `HugoBlobTemplate` 為例，請依您實際的 GitHub 帳號與儲存庫名稱調整
baseURL = "https://eric861129.github.io/HugoBlobTemplate/"
languageCode = "zh-tw"
title = "我的新部落格"

# Hugo 主題設定。如果您的模板是根目錄，可以註解掉或移除此行。
# theme = "hugo-pure-and-simple" 

# 文章列表每頁顯示幾篇文章
paginate = 5

# --- 作者與網站全域參數 ---
[author]
  name = "您的名字"

[params]
  # 網站首頁的描述文字
  description = "歡迎來到我的技術分享與生活點滴。"

  # --- Giscus 留言功能設定 ---
  # 請參考 README 中的教學，到 giscus.app 取得以下四個值
  [params.giscus]
    # 範例：若使用本專案，可填寫 "your-username/HugoBlobTemplate"
    repo = ""
    repoId = ""            # giscus 提供的 repoId
    category = ""          # giscus 討論區的分類名稱
    categoryId = ""        # giscus 提供的 categoryId

  # --- 社群媒體外部連結設定 ---
  # 在側邊欄顯示常用社群或相關網站的連結
  [params.social]
    # 範例：依需求新增或修改名稱與網址
    GitHub = "https://github.com/your-name"
    Twitter = "https://twitter.com/your-name"
